/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulários;

/**
 *
 * @author 02362480143
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnarquivos = new javax.swing.JMenu();
        mnarquivosclientes = new javax.swing.JMenuItem();
        mnarquivosprodutos = new javax.swing.JMenuItem();
        mnarquivosusuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnarquivosaltsenha = new javax.swing.JMenuItem();
        mnarquivosaltusuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnarquivossair = new javax.swing.JMenuItem();
        mnmovimentos = new javax.swing.JMenu();
        mnmovimentosvendas = new javax.swing.JMenuItem();
        mnmovimentosrelatoriovendas = new javax.swing.JMenuItem();
        mnajuda = new javax.swing.JMenu();
        mnajudasobre = new javax.swing.JMenuItem();
        mnajuda2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA JAVA;");

        mnarquivos.setText("Arquivo");

        mnarquivosclientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnarquivosclientes.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\cliente.png")); // NOI18N
        mnarquivosclientes.setText("Clientes");
        mnarquivosclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnarquivosclientesActionPerformed(evt);
            }
        });
        mnarquivos.add(mnarquivosclientes);

        mnarquivosprodutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnarquivosprodutos.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\Produtos.png")); // NOI18N
        mnarquivosprodutos.setText("Produtos");
        mnarquivos.add(mnarquivosprodutos);

        mnarquivosusuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnarquivosusuarios.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\Usuarios.png")); // NOI18N
        mnarquivosusuarios.setText("Usuários");
        mnarquivosusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnarquivosusuariosActionPerformed(evt);
            }
        });
        mnarquivos.add(mnarquivosusuarios);
        mnarquivos.add(jSeparator1);

        mnarquivosaltsenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnarquivosaltsenha.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\password.png")); // NOI18N
        mnarquivosaltsenha.setText("Alterar Senha");
        mnarquivos.add(mnarquivosaltsenha);

        mnarquivosaltusuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnarquivosaltusuario.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\changePassword.png")); // NOI18N
        mnarquivosaltusuario.setText("Alterar Usuario");
        mnarquivos.add(mnarquivosaltusuario);
        mnarquivos.add(jSeparator2);

        mnarquivossair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnarquivossair.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\sair.png")); // NOI18N
        mnarquivossair.setText("Sair");
        mnarquivos.add(mnarquivossair);

        jMenuBar1.add(mnarquivos);

        mnmovimentos.setText("Movimento");

        mnmovimentosvendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        mnmovimentosvendas.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\vendas.png")); // NOI18N
        mnmovimentosvendas.setText("Vendas");
        mnmovimentos.add(mnmovimentosvendas);

        mnmovimentosrelatoriovendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnmovimentosrelatoriovendas.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\relatorio.png")); // NOI18N
        mnmovimentosrelatoriovendas.setText("Relatórios Vendas");
        mnmovimentosrelatoriovendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmovimentosrelatoriovendasActionPerformed(evt);
            }
        });
        mnmovimentos.add(mnmovimentosrelatoriovendas);

        jMenuBar1.add(mnmovimentos);

        mnajuda.setText("Ajuda");

        mnajudasobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnajudasobre.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\about.png")); // NOI18N
        mnajudasobre.setText("Sobre");
        mnajuda.add(mnajudasobre);

        mnajuda2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        mnajuda2.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\ProjetoJava\\ícones\\help.png")); // NOI18N
        mnajuda2.setText("Ajuda");
        mnajuda.add(mnajuda2);

        jMenuBar1.add(mnajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnmovimentosrelatoriovendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmovimentosrelatoriovendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnmovimentosrelatoriovendasActionPerformed

    private void mnarquivosclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnarquivosclientesActionPerformed
       
    }//GEN-LAST:event_mnarquivosclientesActionPerformed

    private void mnarquivosusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnarquivosusuariosActionPerformed
        frmusuarios usuarios = new frmusuarios();
        usuarios.getClass();
    }//GEN-LAST:event_mnarquivosusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnajuda;
    private javax.swing.JMenuItem mnajuda2;
    private javax.swing.JMenuItem mnajudasobre;
    private javax.swing.JMenu mnarquivos;
    private javax.swing.JMenuItem mnarquivosaltsenha;
    private javax.swing.JMenuItem mnarquivosaltusuario;
    private javax.swing.JMenuItem mnarquivosclientes;
    private javax.swing.JMenuItem mnarquivosprodutos;
    private javax.swing.JMenuItem mnarquivossair;
    private javax.swing.JMenuItem mnarquivosusuarios;
    private javax.swing.JMenu mnmovimentos;
    private javax.swing.JMenuItem mnmovimentosrelatoriovendas;
    private javax.swing.JMenuItem mnmovimentosvendas;
    // End of variables declaration//GEN-END:variables
}
